# Generated by Django 4.2.5 on 2024-01-10 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 21, 16, 19, 124508, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена в месяц'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='ram',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оперативная память'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='ssd',
            field=models.IntegerField(blank=True, null=True, verbose_name='Размер SSD хранилища'),
        ),
    ]
