# Generated by Django 4.2.7 on 2024-01-21 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_order_date_created_alter_tariff_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 14, 52, 38, 52936, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
